domain: example.com

records:
  - name: "www"
    type: "CNAME"
    ttl: 60
    values:
      - "web-router.example.com."

  - name: "web-router"
    type: "CNAME"
    ttl: 60
    values:
      - "cf-front.example.com."

  - name: "cf-front"
    type: "CNAME"
    ttl: 300
    values:
      - "example.com."

  - name: "cdn2-front"
    type: "CNAME"
    ttl: 300
    values:
      - "example.b-cdn.net."

  - name: "origin"
    type: "A"
    ttl: 300
    values:
      - "203.0.113.10"
